defmodule BadgeApi.Repo.Migrations.CreateBusinesses do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:businesses, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text)
      add(:email, :text)
      add(:password_hash, :text)
      add(:created_at, :utc_datetime, default: fragment("(now() AT TIME ZONE 'utc')"))
      add(:updated_at, :utc_datetime, default: fragment("(now() AT TIME ZONE 'utc')"))
    end

    create(unique_index(:businesses, [:email], name: "businesses_email_unique_index"))

    create table(:business_api_keys, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:api_key_hash, :text)
      add(:is_active, :boolean, default: true)
      add(:expired_at, :utc_datetime)
      add(:created_at, :utc_datetime, default: fragment("(now() AT TIME ZONE 'utc')"))

      add(
        :business_id,
        references(:businesses,
          column: :id,
          name: "business_api_keys_business_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:business_api_keys, "business_api_keys_business_id_fkey"))

    drop(table(:business_api_keys))

    drop_if_exists(unique_index(:businesses, [:email], name: "businesses_email_unique_index"))

    drop(table(:businesses))
  end
end
